version: "3.9"

services:
  flask_app:
    container_name: flask_app
    image: dockerhub-flask_live_app:1.0.0
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:1029@localhost:5432/laba5_6
    depends_on:
      - flask_db
  flask_db:
    container_name: flask_db
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1029
      - POSTGRES_USER=postgres
      - POSTGRES_DB=laba5_6
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}